export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_FAIL_CONFIRM = 'AUTH_FAIL_CONFIRM';

export const SHOP_FOUND = 'SHOP_FOUND';
export const SHOP_NOT_FOUND = 'SHOP_NOT_FOUND';
export const KEEP_SHOP = 'KEEP_SHOP';
export const SHOPNAME_CHANGED = 'SHOPNAME_CHANGED';
export const ISSTATIC_CHANGED = 'ISSTATIC_CHANGED';

export const ORDER_FETCH_START = 'ORDER_FETCH_START';
export const ORDER_FETCH_SUCCESS = 'ORDER_FETCH_SUCCESS';
export const ORDER_FETCH_FAIL = 'ORDER_FETCH_FAIL'; 

export const ORDER_MORE_FETCH_START = 'ORDER_MORE_FETCH_START';
export const ORDER_MORE_FETCH_SUCCESS_WITHOUT = 'ORDER_MORE_FETCH_SUCCESS_WITHOUT';
export const ORDER_MORE_FETCH_SUCCESS_WITH = 'ORDER_MORE_FETCH_SUCCESS_WITH';
export const ORDER_MORE_FETCH_FAIL = 'ORDER_MORE_FETCH_FAIL'; 

export const UPDATE_START = 'UPDATE_START';
export const UPDATE_FAIL = 'UPDATE_FAIL';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const CLEAR_OLD_ORDERS = 'CLEAR_OLD_ORDERS';
export const CONFIRMED_UPDATE_ERROR = 'CONFIRMED_UPDATE_ERROR';

export const CHECK_DOMAIN_START = 'CHECK_DOMAIN_START';
export const CHECK_DOMAIN_FAIL = 'CHECK_DOMAIN_FAIL';
export const CHECK_DOMAIN_SUCCESS = 'CHECK_DOMAIN_SUCCESS';
export const CHECK_DOMAIN_FAIL_CONFIRM = 'CHECK_DOMAIN_FAIL_CONFIRM';

export const CREATE_SHOP_START = 'CREATE_SHOP_START';
export const CREATE_SHOP_FAIL = 'CREATE_SHOP_FAIL';
export const CREATE_SHOP_SUCCESS = 'CREATE_SHOP_SUCCESS'; 

export const INV_FETCH_START = 'INV_FETCH_START';
export const INV_FETCH_FAIL = 'INV_FETCH_FAIL';
export const INV_FETCH_SUCCESS = 'INV_FETCH_SUCCESS';
export const INV_ERROR_CONFIRM = 'INV_ERROR_CONFIRM'; 

export const INV_UPDATE_START = 'INV_UPDATE_START'; 
export const INV_UPDATE_FAIL = 'INV_UPDATE_FAIL';
export const INV_UPDATE_SUCCESS = 'INV_UPDATE_SUCCESS';

export const PROFILE_FETCH_START = 'PROFILE_FETCH_START';
export const PROFILE_FETCH_FAIL = 'PROFILE_FETCH_FAIL';
export const PROFILE_FETCH_SUCCESS = 'PROFILE_FETCH_SUCCESS';
export const CONFIRMED_PROFILE_ERROR = 'CONFIRMED_PROFILE_ERROR';

export const PROFILE_UPDATE_START = 'PROFILE_UPDATE_START';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';

export const PHOTO_UPLOAD_START = 'PHOTO_UPLOAD_START';
export const PHOTO_UPLOAD_FAIL = 'PHOTO_UPLOAD_FAIL';
export const PHOTO_UPLOAD_SUCCESS = 'PHOTO_UPLOAD_SUCCESS';
export const PHOTO_UPLOAD_CLEAR = 'PHOTO_UPLOAD_CLEAR';
